--고객 정보
INSERT INTO costom_info (ID, PASS, TEL, NAME, ADDRESS, ITEM, LIST, PRICE) VALUES ('ID 1', 'PASS 1', 'TEL 1', 'NAME 1', 'ADDRESS 1', 1, 'ORDER 1', 1);
INSERT INTO costom_info (ID, PASS, TEL, NAME, ADDRESS, ITEM, LIST, PRICE) VALUES ('ID 2', 'PASS 2', 'TEL 2', 'NAME 2', 'ADDRESS 2', 2, 'ORDER 2', 2);

--제품 정보 (상품 , 가격 , 갯수)
INSERT INTO item (ITEM, PRICE, NUM) VALUES (01, 01, 01);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (02, 02, 02);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (03, 03, 03);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (04, 04, 04);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (05, 05, 05);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (06, 06, 06);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (07, 07, 07);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (08, 08, 08);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (09, 09, 09);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (10, 10, 10);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (11, 11, 11);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (12, 12, 12);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (13, 13, 13);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (14, 14, 14);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (15, 15, 15);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (16, 16, 16);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (17, 17, 17);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (18, 18, 18);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (19, 19, 19);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (20, 20, 20);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (21, 21, 21);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (22, 22, 22);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (23, 23, 23);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (24, 24, 24);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (25, 25, 25);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (26, 26, 26);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (27, 27, 27);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (28, 28, 28);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (29, 29, 29);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (30, 30, 30);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (31, 31, 31);
INSERT INTO item (ITEM, PRICE, NUM) VALUES (32, 32, 32);

--구매목록
INSERT INTO ordered (ITEM, NUM, PRICE, STATE) VALUES (1, 1, 1, 'ORDER 1');
INSERT INTO ordered (ITEM, NUM, PRICE, STATE) VALUES (2, 2, 2, 'ORDER 2');
--장바구니

INSERT INTO wish (NUM, PRICE) VALUES (1, 1);
INSERT INTO wish (NUM, PRICE) VALUES (2, 2);
INSERT INTO wish (NUM, PRICE) VALUES (3, 3);